name: pytest
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            version: '0.6.4'
    
        - name: Activate environment
          run: uv venv && source .venv/bin/activate

        - name: Install dependencies
          run: uv sync

        - name: Run tests with coverage
          run: uv run -m pytest --cov=.
        
        - name: Assert >90% coverage
          run: uv run -m coverage report --show-missing --fail-under=90